name: Docker Build and Push

on:
  push:
    branches:
      - dev  # Change this to your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to AWS ECR
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build and Push Docker Image
      run: |
        docker build -t your-ecr-repository-url:latest .
        docker tag your-ecr-repository-url:latest ${{ secrets.AWS_ECR_REGISTRY_URL }}/your-ecr-repository-url:latest
        docker push ${{ secrets.AWS_ECR_REGISTRY_URL }}/your-ecr-repository-url:latest
